# Generated by Django 4.1.7 on 2023-06-04 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_year_of_construction_movie_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-publish']},
        ),
        migrations.AddField(
            model_name='movie',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('coming soon', 'Coming soon'), ('published', 'Published')], default='published', max_length=100),
        ),
    ]
