# Generated by Django 4.1.7 on 2023-06-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_trailer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='img',
            new_name='img1',
        ),
        migrations.AddField(
            model_name='movie',
            name='img2',
            field=models.ImageField(null=True, upload_to='news_photos'),
        ),
        migrations.AddField(
            model_name='movie',
            name='img3',
            field=models.ImageField(null=True, upload_to='news_photos'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_banner',
            field=models.ImageField(null=True, upload_to='news_photos'),
        ),
    ]
