# Generated by Django 4.1.7 on 2023-06-07 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_rename_img_movie_img1_movie_img2_movie_img3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='img1',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_banner',
        ),
    ]
