# Generated by Django 4.1.7 on 2023-06-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_rename_img1_movie_img_remove_movie_img2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='news_photos'),
        ),
        migrations.AddField(
            model_name='movie',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='news_photos'),
        ),
        migrations.AddField(
            model_name='movie',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='news_photos'),
        ),
    ]
