# Generated by Django 4.1.7 on 2023-06-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_movie_img2_movie_img3_movie_img4'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Family_guide',
            field=models.TextField(blank=True, null=True),
        ),
    ]
