# Generated by Django 4.1.7 on 2023-06-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_movie_family_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_file',
            field=models.FileField(blank=True, null=True, upload_to='movie_file'),
        ),
    ]
