# Generated by Django 4.1.7 on 2023-06-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_category_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
