# Generated by Django 4.1.7 on 2023-06-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_alter_movie_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='company',
        ),
        migrations.AddField(
            model_name='movie',
            name='company',
            field=models.ManyToManyField(related_name='company', to='movie.company'),
        ),
    ]
