# Generated by Django 4.1.7 on 2023-06-24 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_remove_movie_company_movie_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='company',
        ),
    ]
