# Generated by Django 4.1.7 on 2023-06-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_movie_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='special_offers',
            field=models.BooleanField(default=False),
        ),
    ]
