# Generated by Django 4.2.4 on 2023-08-23 07:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('slug', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('no_of_peaple', models.CharField(max_length=20)),
                ('request', models.TextField()),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.table')),
            ],
        ),
    ]
