# Generated by Django 4.2.4 on 2023-08-24 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_rename_no_of_peaple_reserve_no_of_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reserve.table'),
        ),
    ]
