# Generated by Django 4.2.4 on 2023-08-24 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_alter_reserve_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reserve.table'),
        ),
    ]
