# Generated by Django 4.2.4 on 2023-08-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_alter_reserve_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='time',
        ),
        migrations.AddField(
            model_name='reserve',
            name='time',
            field=models.ManyToManyField(related_name='time', to='reserve.table'),
        ),
    ]
