# Generated by Django 4.2.4 on 2023-08-20 05:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('title', models.CharField(max_length=25)),
                ('detail', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media')),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('B', 'breakfast'), ('L', 'lunch'), ('D', 'dinner')], max_length=1)),
                ('slug', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
    ]
