# Generated by Django 4.2.4 on 2023-08-21 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_profile_address_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_name',
        ),
    ]
