# Generated by Django 4.2.4 on 2023-08-20 07:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='media')),
                ('facebooke', models.URLField(blank=True, null=True)),
                ('X', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('slug', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
    ]
