# Generated by Django 4.2.4 on 2023-08-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefs',
            name='image',
        ),
    ]
