# Generated by Django 4.2.4 on 2023-08-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_chefs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefs',
            name='image',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
