# Generated by Django 4.2.3 on 2023-07-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('A', 'active'), ('C', 'completed')], max_length=1)),
                ('position', models.IntegerField()),
            ],
            options={
                'ordering': ['-position'],
            },
        ),
    ]
