# Generated by Django 4.2.3 on 2023-07-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={},
        ),
        migrations.RemoveField(
            model_name='list',
            name='position',
        ),
        migrations.AlterField(
            model_name='list',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'active'), ('C', 'completed')], max_length=1, null=True),
        ),
    ]
