# Generated by Django 4.2.3 on 2023-07-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_list_options_remove_list_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='status',
        ),
        migrations.AddField(
            model_name='list',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
