# Generated by Django 5.0.6 on 2024-05-25 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('offer', models.IntegerField()),
                ('count', models.IntegerField()),
                ('picture', models.ImageField(upload_to='product/')),
                ('description', models.TextField()),
                ('tag', models.CharField(choices=[('N', 'New'), ('S', 'Sale')], max_length=1)),
                ('avaible', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
    ]
