# Generated by Django 4.1.7 on 2023-08-15 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('slug', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='media')),
                ('label', models.CharField(choices=[('Speciall offer', 'speciall offer'), ('Best seller', 'best seller'), ('New', 'new')], max_length=14)),
                ('gender', models.CharField(choices=[('F', 'female'), ('M', 'man')], max_length=1)),
                ('slug', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('status', models.CharField(choices=[('Paid', 'paid'), ('Unpaid', 'unpaid')], max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('price', models.IntegerField()),
                ('slug', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutOrder',
            fields=[
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=300)),
                ('adress', models.TextField()),
                ('country', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('zipcode', models.CharField(max_length=250)),
                ('name_on_card', models.CharField(max_length=250)),
                ('credit_card_number', models.IntegerField()),
                ('Expiration', models.DateField()),
                ('CVV', models.IntegerField()),
                ('slug', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
