# Generated by Django 5.0.6 on 2024-05-23 09:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramGallery',
            fields=[
                ('image', models.ImageField(upload_to='media/instagram_gallery/')),
                ('link', models.URLField()),
                ('slug', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
    ]
