# Generated by Django 5.0.6 on 2024-05-23 10:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='team/')),
                ('facebook', models.URLField()),
                ('x', models.URLField()),
                ('gmail', models.URLField()),
                ('youtube', models.URLField()),
                ('slug', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
    ]
