# Generated by Django 5.0.6 on 2024-05-23 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tema'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tema',
            new_name='Team',
        ),
    ]
