# Generated by Django 5.0.6 on 2024-05-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_team_facebook_alter_team_gmail_alter_team_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
