# Generated by Django 4.2.5 on 2023-11-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_avable', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
