# Generated by Django 4.2.5 on 2023-11-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='##.##', max_digits=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(help_text='name of product', max_length=50),
        ),
    ]
