# Generated by Django 4.1.7 on 2023-08-16 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('status', models.CharField(choices=[('p', 'منتشر شده'), ('d', 'منتشر نشده')], max_length=1, verbose_name='وضعیت')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('image', models.ImageField(upload_to='media', verbose_name='تصویر')),
                ('slug', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='شاخصه')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-time'],
            },
        ),
    ]
