# Generated by Django 5.0.1 on 2024-03-15 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام کالا')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('author', models.CharField(max_length=50, verbose_name='نویسنده')),
                ('image', models.ImageField(upload_to='media/products', verbose_name='تصویر')),
                ('page_count', models.IntegerField(verbose_name='تعداد صفحه')),
                ('publication_date', models.CharField(max_length=50, verbose_name='سال انتشار')),
                ('book_cover', models.CharField(max_length=50, verbose_name='نوع جلد')),
                ('tag', models.CharField(choices=[('H', 'فروش داغ'), ('D', 'تخفیف ویژه'), ('N', 'جدید')], max_length=1, verbose_name='تگ')),
                ('price', models.IntegerField(help_text='به تومان', verbose_name='قیمت')),
                ('discount', models.IntegerField(help_text='چند درصد تخفیف خورده', verbose_name='درصد تخفیف')),
                ('availble', models.BooleanField(default=True, verbose_name='موجود')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('status', models.CharField(choices=[('P', 'در حال بررسی'), ('PR', 'در حال اماده سازی'), ('S', 'ارسال شده'), ('D', 'تحویل داده شده')], max_length=2, verbose_name='وضعیت')),
                ('slug', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.profile', verbose_name='خریدار')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
    ]
