# Generated by Django 4.2.7 on 2023-11-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_alter_table_options_remove_table_point'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={},
        ),
        migrations.RemoveField(
            model_name='table',
            name='place',
        ),
    ]
