# Generated by Django 4.2.7 on 2023-11-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_alter_table_options_remove_table_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='draw',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='table',
            name='win',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
