# Generated by Django 4.2.7 on 2023-11-24 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_alter_table_draw_alter_table_win'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['-win']},
        ),
    ]
