# Generated by Django 4.2.7 on 2023-11-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_alter_table_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={},
        ),
    ]
