# Generated by Django 4.2.7 on 2023-11-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_alter_table_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='point',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
