# Generated by Django 4.2.7 on 2023-11-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_table_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='point',
        ),
    ]
