# Generated by Django 4.2.7 on 2023-11-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_remove_table_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='point',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
