# Generated by Django 4.2.7 on 2023-11-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_table_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
