# Generated by Django 4.2.7 on 2023-11-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_alter_table_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
