# Generated by Django 4.2.1 on 2023-06-02 07:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socialplatform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='images-posts')),
                ('caption', models.TextField()),
                ('dtime', models.DateTimeField(auto_now_add=True)),
                ('no_likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='image.png', upload_to='user_images'),
        ),
    ]
