# Generated by Django 4.2.1 on 2023-06-02 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialplatform', '0002_post_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='username',
        ),
    ]
