# Generated by Django 4.1.7 on 2023-07-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialplatform', '0006_comment_slug_alter_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
