# Generated by Django 5.0.5 on 2024-05-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('small_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('medium_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('large_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('image', models.ImageField(upload_to='media')),
                ('is_avaible', models.BooleanField(default=False)),
            ],
        ),
    ]
