# Generated by Django 4.1.7 on 2023-04-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('Available', 'available'), ('unavailable', 'Unvaibale')], default='Special offers', max_length=100),
        ),
    ]
