# Generated by Django 4.1.7 on 2023-04-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_specialoffers_delete_food'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialoffers',
            new_name='Food',
        ),
    ]
