# Generated by Django 4.1.7 on 2023-04-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast',
            name='img',
            field=models.ImageField(null=True, upload_to='news_photos'),
        ),
        migrations.AddField(
            model_name='dinner',
            name='img',
            field=models.ImageField(null=True, upload_to='news_photos'),
        ),
        migrations.AddField(
            model_name='food',
            name='img',
            field=models.ImageField(null=True, upload_to='news_photos'),
        ),
        migrations.AddField(
            model_name='lunch',
            name='img',
            field=models.ImageField(null=True, upload_to='news_photos'),
        ),
    ]
